server:
  port: 8086 # 端口

spring:
  application:
    name: ms-points # 应用名
  # 数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: feng20010729
    url: jdbc:mysql://119.91.229.58:3306/db_imooc?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    hikari:
      maximum-pool-size: 10
      idle-timeout: 500000
  # Redis
  redis:
    port: 6379
    host: 119.91.229.58
    timeout: 3000
    database: 3
    password: 123456
  # Swagger
  swagger:
    base-package: com.imooc.points
    title: 小莫美食社交食客API接口文档


# 配置 Eureka Server 注册中心
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

service:
  name:
    ms-oauth-server: http://ms-oauth2-server/
    ms-diners-server: http://ms-diners/

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  pattern:
    console: '%d{2100-01-01 13:14:00.666} [%thread] %-5level %logger{50} - %msg%n'